### ISSUE TITLE
BFS-powered kernel

### ISSUE THREAD

**Issue by g7** [semplice/project-breathe#5]
A Brain Fuck Scheduler-powered kernel with also other optimizations for a desktop system.

**Comment by g7** [comment]
Using BFQ as the default I/O scheduler would be nice, too.

Eugenio

**Comment by r3vn** [comment]
BFS-Powered kernel ready: https://github.com/semplice/Semplice-kernel but need to be tested.

Giuseppe

**Comment by g7** [comment]
It has been decided to base our efforts on the pf-kernel. Packaging is there and the kernel works (even if it was not tested in live). This bug can now be closed.

https://github.com/semplice/pf-kernel/tree/debian

Eugenio
